// <auto-generated />
using System;
using FactoryWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220208112618_updateForemployeeshift")]
    partial class updateForemployeeshift
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FactoryWebsite.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Manager")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FactoryWebsite.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartWorkYear")
                        .HasColumnType("int");

                    b.Property<int?>("departmentID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("departmentID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FactoryWebsite.Models.EmployeeShift", b =>
                {
                    b.Property<int>("EsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EsId"), 1L, 1);

                    b.Property<int?>("Employee_1EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<int>("Shift_id")
                        .HasColumnType("int");

                    b.HasKey("EsId");

                    b.HasIndex("Employee_1EmployeeID");

                    b.ToTable("EmployeeShifts");
                });

            modelBuilder.Entity("FactoryWebsite.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FactoryWebsite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfActions")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FactoryWebsite.Models.Employee", b =>
                {
                    b.HasOne("FactoryWebsite.Models.Department", "Department_1")
                        .WithMany("EmployeesList")
                        .HasForeignKey("departmentID");

                    b.Navigation("Department_1");
                });

            modelBuilder.Entity("FactoryWebsite.Models.EmployeeShift", b =>
                {
                    b.HasOne("FactoryWebsite.Models.Employee", "Employee_1")
                        .WithMany("Employee_Shift_1")
                        .HasForeignKey("Employee_1EmployeeID");

                    b.Navigation("Employee_1");
                });

            modelBuilder.Entity("FactoryWebsite.Models.Department", b =>
                {
                    b.Navigation("EmployeesList");
                });

            modelBuilder.Entity("FactoryWebsite.Models.Employee", b =>
                {
                    b.Navigation("Employee_Shift_1");
                });
#pragma warning restore 612, 618
        }
    }
}
